name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *"  # chạy vào phút 0 mỗi 12 giờ
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: 🔄 Checkout repository
        uses: actions/checkout@v3

      - name: 🟡 Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: 📂 Move SVG to dist folder
        run: |
          mkdir -p dist
          mv pacman-contribution-graph.svg dist/

      - name: 🚀 Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Update pacman contribution graph [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
